apiVersion: v1
kind: Service
metadata:
    name: bookstore-backend
    labels:
        name: bookstore-backend-service
        app: bookstore
spec:
    type: NodePort
    ports:
        - port: 8080
          targetPort: 8080
          nodePort: 30005
    selector:
        name: bookstore-backend-pod
        app: bookstore

