version: '3.9'

services:
  db:
    container_name: bookstore_db
    build: ./postgresql
    ports:
      - 5432:5432

  backend:
    container_name: bookstore_backend
    build: .
    ports:
      - 8080:8080

  frontend:
    container_name: bookstore_frontend
    build: ./bookstore-react
    ports:
      - 3000:3000
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - /app/node_modules
      - ./bookstore-react/src:/app/src
    stdin_open: true
    tty: true