version: '3.9'

services:
  bookstore_db:
    container_name: bookstore_db
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Bookstore
    volumes:
       - ./postgresql/create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
       - ./postgresql/fill-table.sql:/docker-entrypoint-initdb.d/fill-table.sql

  backend:
    container_name: bookstore_backend
    build: .
    ports:
      - 8080:8080

  frontend:
    container_name: bookstore_frontend
    build: ./bookstore-react
    ports:
      - 3000:3000
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - /app/node_modules
      - ./bookstore-react/src:/app/src
    stdin_open: true
    tty: true