apiVersion: v1
kind: Service
metadata:
    name: bookstore-frontend
    labels:
        name: bookstore-frontend-service
        app: bookstore
spec:
    type: NodePort
    ports:
        - port: 3000
          targetPort: 3000
          nodePort: 30004
    selector:
        name: bookstore-frontend-pod
        app: bookstore

